"""Public API for the HP fan-control daemon."""

from .cli import (
    AUTO_GUARD_PATH,
    CONFIGURATION_ERROR_EXIT_STATUS,
    acquire_lock,
    dry_run_lock_path,
    ensure_failsafe_fan_state,
    main,
    parse_args,
    restore_firmware_auto,
    run_actuator_test,
)
from .config import (
    ConfigurationError,
    Curve,
    Settings,
    hp_factory_performance_curves,
    hp_level_percent,
    percent_to_pwm,
    pwm_to_percent,
)
from .controller import ControlPolicy, Controller, CsvLog, Ewma, SystemdNotifier
from .hardware import (
    AUTO_MODE,
    MANUAL_MODE,
    MAX_MODE,
    HardwareError,
    HardwareNotReadyError,
    HpFanHwmon,
    PlatformProfileMonitor,
    Sensors,
    TemperatureSnapshot,
    read_hp_wmi_ir_temperature,
    validate_required_profile,
    wait_for_hp_fan_hwmon,
)

__all__ = (
    "AUTO_GUARD_PATH",
    "AUTO_MODE",
    "CONFIGURATION_ERROR_EXIT_STATUS",
    "MANUAL_MODE",
    "MAX_MODE",
    "ConfigurationError",
    "ControlPolicy",
    "Controller",
    "CsvLog",
    "Curve",
    "Ewma",
    "HardwareError",
    "HardwareNotReadyError",
    "HpFanHwmon",
    "PlatformProfileMonitor",
    "Sensors",
    "Settings",
    "SystemdNotifier",
    "TemperatureSnapshot",
    "acquire_lock",
    "dry_run_lock_path",
    "ensure_failsafe_fan_state",
    "hp_factory_performance_curves",
    "hp_level_percent",
    "main",
    "parse_args",
    "percent_to_pwm",
    "pwm_to_percent",
    "read_hp_wmi_ir_temperature",
    "restore_firmware_auto",
    "run_actuator_test",
    "validate_required_profile",
    "wait_for_hp_fan_hwmon",
)
